import "./globals.css";
import NavigationBar from "@/components/Navbar";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <NavigationBar />
      <body className="w-full h-full flex flex-col items-center font-pretendard">{children}</body>
    </html>
  )
}
